import "./globals.css";

import { Comfortaa } from "next/font/google";
import type { Metadata } from "next";
import MobileLayout from "./_mobileLayout";

const comfortaa = Comfortaa({
  subsets: ["latin", "latin-ext"], // Türkçe karakterler için
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-comfortaa",
});

// const quicksand = Quicksand({
//   subsets: ["latin", "latin-ext"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-quicksand",
// });

// const nunito = Nunito({
//   subsets: ["latin", "latin-ext"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-nunito",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comfortaa.variable} ${comfortaa.variable} antialiased`}
      >
        <MobileLayout>{children}</MobileLayout>
      </body>
    </html>
  );
}
