import { MockDataService } from "./models";

export const mockDataService: MockDataService = {
  teacher: {
    name: "Ayşe Öğretmen",
    email: "ayse.ogretmen@okul.edu.tr",
    profilePhoto:
      "https://static.vecteezy.com/system/resources/previews/049/005/561/non_2x/profile-shot-of-a-beautiful-young-brunette-with-wind-swept-hair-against-a-white-backdrop-photo.jpg",
  },

  classes: [
    {
      id: 1,
      name: "Papatyalar",
      image:
        "https://www.zengardentr.com/shop/ir/87/myassets/products/460/yayilici-papatya-tohumu-creeping-daisy-1.jpg?revision=1735808859",
      color: "bg-yellow-100",
      accent: "bg-yellow-200",
      icon: "🌼",
    },
    {
      id: 2,
      name: "Sümbüller",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR0VPAX62LBjGQ4CPU9ja8kW3Hab-KdO-U1Q&s",
      color: "bg-purple-100",
      accent: "bg-purple-200",
      icon: "🌷",
    },
    {
      id: 3,
      name: "Güller",
      image:
        "https://letspepapp.com/wp-content/uploads/2021/03/biel-morro-kcKiBcDTJt4-unsplash-1152x766.jpg",
      color: "bg-pink-100",
      accent: "bg-pink-200",
      icon: "🌹",
    },
    {
      id: 4,
      name: "Laleler",
      image:
        "https://www.cokilgincbilgiler.com/FileUpload/ks650858/File/lale.jpg",
      color: "bg-red-100",
      accent: "bg-red-200",
      icon: "🌷",
    },
    {
      id: 5,
      name: "Menekşeler",
      image: "https://www.muridan.com/resimler/icerikler/541.jpg",
      color: "bg-indigo-100",
      accent: "bg-indigo-200",
      icon: "🌺",
    },
  ],

  students: {
    1: [
      {
        id: 1,
        name: "Ahmet Yılmaz",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Fatma Yılmaz",
        parentPhone: "0532 123 4567",
      },
      {
        id: 2,
        name: "Ayşe Demir",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Mehmet Demir",
        parentPhone: "0533 234 5678",
      },
      {
        id: 3,
        name: "Mehmet Öz",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Zeynep Öz",
        parentPhone: "0534 345 6789",
      },
      {
        id: 4,
        name: "Fatma Kara",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Ali Kara",
        parentPhone: "0535 456 7890",
      },
      {
        id: 5,
        name: "Ali Şahin",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Emine Şahin",
        parentPhone: "0536 567 8901",
      },
      {
        id: 6,
        name: "Emine Çelik",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Hasan Çelik",
        parentPhone: "0537 678 9012",
      },
      {
        id: 7,
        name: "Hasan Yıldız",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Aysel Yıldız",
        parentPhone: "0538 789 0123",
      },
      {
        id: 8,
        name: "Zeynep Aydın",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Osman Aydın",
        parentPhone: "0539 890 1234",
      },
      {
        id: 9,
        name: "Osman Güzel",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Hacer Güzel",
        parentPhone: "0540 901 2345",
      },
      {
        id: 10,
        name: "Hacer Polat",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "İsmail Polat",
        parentPhone: "0541 012 3456",
      },
      {
        id: 11,
        name: "İsmail Çakır",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Ayten Çakır",
        parentPhone: "0542 123 4567",
      },
      {
        id: 12,
        name: "Ayten Koç",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Mustafa Koç",
        parentPhone: "0543 234 5678",
      },
      {
        id: 13,
        name: "Mustafa Eren",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Serpil Eren",
        parentPhone: "0544 345 6789",
      },
      {
        id: 14,
        name: "Serpil Kaya",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Kemal Kaya",
        parentPhone: "0545 456 7890",
      },
      {
        id: 15,
        name: "Kemal Uzun",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Meral Uzun",
        parentPhone: "0546 567 8901",
      },
    ],
    2: [
      {
        id: 16,
        name: "Meral Acar",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Necdet Acar",
        parentPhone: "0547 678 9012",
      },
      {
        id: 17,
        name: "Necdet Doğan",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Sevgi Doğan",
        parentPhone: "0548 789 0123",
      },
      {
        id: 18,
        name: "Sevgi Bulut",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Ramazan Bulut",
        parentPhone: "0549 890 1234",
      },
      {
        id: 19,
        name: "Ramazan Çetin",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Gülsüm Çetin",
        parentPhone: "0550 901 2345",
      },
      {
        id: 20,
        name: "Gülsüm Bayrak",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Ömer Bayrak",
        parentPhone: "0551 012 3456",
      },
    ],
    3: [
      {
        id: 21,
        name: "Ömer Aslan",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Hatice Aslan",
        parentPhone: "0552 123 4567",
      },
      {
        id: 22,
        name: "Hatice Güneş",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Yusuf Güneş",
        parentPhone: "0553 234 5678",
      },
      {
        id: 23,
        name: "Yusuf Taş",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Nurcan Taş",
        parentPhone: "0554 345 6789",
      },
      {
        id: 24,
        name: "Nurcan Kılıç",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Cengiz Kılıç",
        parentPhone: "0555 456 7890",
      },
      {
        id: 25,
        name: "Cengiz Aktaş",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Selma Aktaş",
        parentPhone: "0556 567 8901",
      },
    ],
    4: [
      {
        id: 26,
        name: "Selma Erdem",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Recep Erdem",
        parentPhone: "0557 678 9012",
      },
      {
        id: 27,
        name: "Recep Özkan",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Filiz Özkan",
        parentPhone: "0558 789 0123",
      },
      {
        id: 28,
        name: "Filiz Şen",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Hakan Şen",
        parentPhone: "0559 890 1234",
      },
      {
        id: 29,
        name: "Hakan Vural",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Tülay Vural",
        parentPhone: "0560 901 2345",
      },
      {
        id: 30,
        name: "Tülay Öztürk",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Salih Öztürk",
        parentPhone: "0561 012 3456",
      },
    ],
    5: [
      {
        id: 31,
        name: "Salih Çiftçi",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Elif Çiftçi",
        parentPhone: "0562 123 4567",
      },
      {
        id: 32,
        name: "Elif Kayhan",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Murat Kayhan",
        parentPhone: "0563 234 5678",
      },
      {
        id: 33,
        name: "Murat Avcı",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Seda Avcı",
        parentPhone: "0564 345 6789",
      },
      {
        id: 34,
        name: "Seda Yaşar",
        photo: "/api/placeholder/80/80",
        age: 7,
        parentName: "Bülent Yaşar",
        parentPhone: "0565 456 7890",
      },
      {
        id: 35,
        name: "Bülent Çakar",
        photo: "/api/placeholder/80/80",
        age: 6,
        parentName: "Nihal Çakar",
        parentPhone: "0566 567 8901",
      },
    ],
  },

  medications: {
    1: [
      { id: 1, name: "Vitamin D3", time: "09:00", taken: true },
      { id: 2, name: "Demir Şurubu", time: "14:00", taken: true },
      { id: 3, name: "Kalsiyum", time: "19:00", taken: false },
    ],
    2: [
      { id: 4, name: "Multivitamin", time: "08:30", taken: true },
      { id: 5, name: "Omega 3", time: "20:00", taken: false },
    ],
    16: [
      { id: 6, name: "Probiyotik", time: "10:00", taken: false },
      { id: 7, name: "Çinko", time: "16:00", taken: true },
    ],
  },

  dailyReports: {
    1: {
      kahvalti: "yedi",
      ogleYemegi: null,
      ikindi: "az-yedi",
      etkinlikKatilimi: null,
      duyguDurumu: "mutlu",
      genelUyum: "uyumlu",
      arkadaslarlaIletisim: "iyi",
    },
    2: {
      kahvalti: "az-yedi",
      ogleYemegi: "yedi",
      ikindi: "yemedi",
      etkinlikKatilimi: "kismen-katildi",
      duyguDurumu: "az-mutlu",
      genelUyum: "kismen-uyumlu",
      arkadaslarlaIletisim: "orta",
    },
    16: {
      kahvalti: "yedi",
      ogleYemegi: "yedi",
      ikindi: "yedi",
      etkinlikKatilimi: "katildi",
      duyguDurumu: "mutlu",
      genelUyum: "uyumlu",
      arkadaslarlaIletisim: "iyi",
    },
  },

  iconMapping: {
    yemek: {
      yedi: { icon: "Check", color: "text-green-600", bgColor: "bg-green-100" },
      "az-yedi": {
        icon: "Minus",
        color: "text-yellow-600",
        bgColor: "bg-yellow-100",
      },
      yemedi: { icon: "X", color: "text-red-600", bgColor: "bg-red-100" },
    },
    etkinlik: {
      katildi: {
        icon: "Check",
        color: "text-green-600",
        bgColor: "bg-green-100",
      },
      "kismen-katildi": {
        icon: "AlertCircle",
        color: "text-yellow-600",
        bgColor: "bg-yellow-100",
      },
      katilmadi: { icon: "X", color: "text-red-600", bgColor: "bg-red-100" },
    },
    duygu: {
      mutlu: {
        icon: "Smile",
        color: "text-green-600",
        bgColor: "bg-green-100",
      },
      "az-mutlu": {
        icon: "Meh",
        color: "text-yellow-600",
        bgColor: "bg-yellow-100",
      },
      mutsuz: { icon: "Frown", color: "text-red-600", bgColor: "bg-red-100" },
    },
    uyum: {
      uyumlu: {
        icon: "Star",
        color: "text-green-600",
        bgColor: "bg-green-100",
      },
      "kismen-uyumlu": {
        icon: "AlertTriangle",
        color: "text-yellow-600",
        bgColor: "bg-yellow-100",
      },
      uyumsuz: {
        icon: "XCircle",
        color: "text-red-600",
        bgColor: "bg-red-100",
      },
    },
    iletisim: {
      iyi: { icon: "Heart", color: "text-green-600", bgColor: "bg-green-100" },
      orta: {
        icon: "Users",
        color: "text-yellow-600",
        bgColor: "bg-yellow-100",
      },
      kotu: { icon: "UserX", color: "text-red-600", bgColor: "bg-red-100" },
    },
  },
};
